version: "3"
services:
  app:
    container_name: app_rota
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    links:
      - "mongo_rota:mongohost"
  mongo_rota:
    container_name: mongo_rota
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
